/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

//import static java.lang.String.format;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faychan
 */
public class formsis extends javax.swing.JFrame {

    /**
     * Creates new form formsis
     */
    public formsis() {
        initComponents();
        setDate(); setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ltime = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        b5 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        ltime.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ltime.setText("Time:");
        jPanel1.add(ltime);
        ltime.setBounds(780, 50, 254, 28);

        ldate.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ldate.setText("Date:");
        jPanel1.add(ldate);
        ldate.setBounds(780, 20, 254, 28);

        jLabel10.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel10.setText("Rheinisch-Westfälische Technische Hochschule Aachen");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 20, 560, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1170, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("ah");
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT DATA INPUT ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 160, 40);
        jPanel2.add(tf1);
        tf1.setBounds(10, 70, 170, 29);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel2.setText("Birthdate");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 300, 70, 30);
        jPanel2.add(tf3);
        tf3.setBounds(10, 260, 164, 29);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel3.setText("Grade");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 360, 50, 30);
        jPanel2.add(tf4);
        tf4.setBounds(10, 390, 164, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 420, 37, 30);
        jPanel2.add(tf5);
        tf5.setBounds(10, 450, 164, 30);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 490, 60, 20);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 170, 70, 30);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 510, 166, 100);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        rb1.setText("Gent");
        jPanel2.add(rb1);
        rb1.setBounds(20, 200, 59, 27);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        rb2.setText("Lady");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel2.add(rb2);
        rb2.setBounds(90, 200, 57, 27);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel7.setText("NIS");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 40, 30, 20);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(230, 50));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 230, 10);

        jLabel8.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 110, 70, 30);

        jLabel9.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel9.setText("Birthplace");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 230, 130, 30);
        jPanel2.add(tf2);
        tf2.setBounds(10, 140, 164, 29);
        jPanel2.add(date1);
        date1.setBounds(10, 330, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 220, 620);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        b5.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b5.setText("EDIT");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel3.add(b5);
        b5.setBounds(540, 10, 110, 40);

        b1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b1.setText("SAVE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel3.add(b1);
        b1.setBounds(10, 10, 110, 40);

        b2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b2.setText("DELETE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel3.add(b2);
        b2.setBounds(140, 10, 110, 40);

        b3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b3.setText("CLEAR");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);
        b3.setBounds(270, 10, 110, 40);

        b4.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b4.setText("REFRESH");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel3.add(b4);
        b4.setBounds(400, 10, 120, 40);

        b6.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b6.setText("PRINT");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel3.add(b6);
        b6.setBounds(670, 10, 110, 40);

        b7.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b7.setText("EXIT");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel3.add(b7);
        b7.setBounds(800, 10, 110, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(250, 100, 930, 60);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Name", "Gender", "Birthplace", "Birthdate", "Grade", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 13, 910, 510);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 170, 930, 550);

        setSize(new java.awt.Dimension(1209, 774));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        ta1.setText("");
        date1.setDate(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_b3ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(date1.getDate());
        if("".equals(tf1.getText()) || "".equals(tf2.getText()) || date.equals("")
                ||"".equals(tf3.getText()) || "".equals(tf4.getText()) 
                || "".equals(tf5.getText()) || "".equals(ta1.getText())){
            JOptionPane.showMessageDialog(this, "Please, Fill Data", "Error", JOptionPane.WARNING_MESSAGE);           
        } else {
            String Ge = "";
            if (rb1.isSelected()){
                Ge = "M";
            } else if (rb2.isSelected()){
                Ge = "F";
            } else {
                JOptionPane.showMessageDialog(this, "Please, Select Radio Button", "Error", JOptionPane.WARNING_MESSAGE);
            }
            String SQL = "INSERT INTO t_siswa (NIS, Name, Gender,Birthplace, Birthdate, Grade, Email, Address)" 
                    + "VALUES ('"+tf1.getText()+"','"+tf2.getText()+ "','"
                    +Ge+"', '"+tf3.getText()+"','"+date+"','"
                    +tf4.getText()+"','"+tf5.getText()+"','"+ta1.getText()+"')";
            int status = connectDB.execute(SQL);
        
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);           
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add", "Error", JOptionPane.WARNING_MESSAGE);           
            }
        }
            
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        int row = tb1.getSelectedRow();
        if (row != -1){
            String NIS = tb1.getValueAt(row, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = connectDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data Erased Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);           
            }else {
                JOptionPane.showMessageDialog(this, "Data Failed to Erase", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, Select the Row First", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        selectData();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(date1.getDate());
        if("".equals(tf1.getText()) || "".equals(tf2.getText()) || date.equals("")
                ||"".equals(tf3.getText()) || "".equals(tf4.getText()) 
                || "".equals(tf5.getText()) || "".equals(ta1.getText())){
            JOptionPane.showMessageDialog(this, "Please, Fill Data", "Error", JOptionPane.WARNING_MESSAGE);           
        } else {
            String Ge = "";
            if (rb1.isSelected()){
                Ge = "M";
            } else if (rb2.isSelected()){
                Ge = "F";
            } else {
                JOptionPane.showMessageDialog(this, "Please, Select Radio Button", "Error", JOptionPane.WARNING_MESSAGE);
            }
            int row = tb1.getSelectedRow();
            String nis = tb1.getValueAt(row,0).toString();
            String SQL = "UPDATE t_siswa SET `NIS`='"+tf1.getText()
                    + "',`Name`='"+tf2.getText()
                    + "',`Gender`='"+Ge
                    + "',`Birthplace`='"+tf3.getText()
                    + "',`Birthdate`='"+date
                    + "',`Grade`='"+tf4.getText()
                    + "',`Email`='"+tf5.getText()
                    + "',`Address`='"+ta1.getText()
                    +"' WHERE NIS="+nis;
            int status = connectDB.execute(SQL);
            
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Edited Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add", "Error", JOptionPane.WARNING_MESSAGE);           
            }
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int row = tb1.getSelectedRow();
        
        if(row != -1){
            tf1.setText(tb1.getValueAt(row, 0).toString());
            tf2.setText(tb1.getValueAt(row, 1).toString());
            if("Male".equals(tb1.getValueAt(row, 2).toString())){
                rb1.setSelected(true);                
            } else {
                rb2.setSelected(true);
            }
            tf3.setText(tb1.getValueAt(row, 3).toString());
            
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tb1.getValueAt(row, 4).toString());
            } catch (ParseException ex) {
                Logger.getLogger(formsis.class.getName()).log(Level.SEVERE, null, ex);
            }

            date1.setDate(dateFormat);
            tf4.setText(tb1.getValueAt(row, 5).toString());
            tf5.setText(tb1.getValueAt(row, 6).toString());
            ta1.setText(tb1.getValueAt(row, 7).toString());
            
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        MessageFormat header = new MessageFormat("Telkom Vocational Highschool Students Identity");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}     ");
        
        try {
            tb1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null,true);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_b7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formsis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formsis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formsis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formsis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formsis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel ltime;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String C[] = {"NIS", "Name", "Gender","Birthplace", "Birthdate", "Grade", "Email", "Address"};
        DefaultTableModel dtm = new DefaultTableModel(null, C);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs= connectDB.executeQuery(SQL);
        
        try {
            while(rs.next()) {
                String NIS = rs.getString(1);
                String Name = rs.getString(2);
                String Gender = "";
                if ("M".equals(rs.getString(3))) {
                    Gender = "Male";
                } else {
                    Gender = "Female";
                }
                String Birthplace = rs.getString(4);
                String Birthdate = rs.getString(5);
                String Grade = rs.getString(6);
                String Email = rs.getString(7);
                String Address = rs.getString(8);
                String data[] = {NIS, Name, Gender, Birthplace, Birthdate, Grade, Email, Address};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(formsis.class.getName()).log(Level.SEVERE, null, ex);
        } tb1.setModel(dtm);
    }
public void setDate(){
    java.util.Date now = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
    ldate.setText(kal.format(now));
    }

public void setTime(){
    ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nolh = "";
                String nolm = "";
                String nols = "";
                
                
                Date dt = new Date();
                int vh = dt.getHours();
                int vm = dt.getMinutes();
                int vs = dt.getSeconds();
                
                if (vh<=9){
                    nolh = "0";
                } if (vm <= 9) {
                    nolm = "0";
                } if (vs <= 9){
                    nols = "0";
                }
               
                
                String h = nolh + Integer.toString(vh);
                String m = nolm + Integer.toString(vm);
                String s = nols + Integer.toString(vs);
                ltime.setText(h+":"+m+":"+s);
            }
        };
    new Timer(100, taskPerformer).start();
}
}


